#--------------------------
# dojo profile config
# https://book.dojoengine.org/framework/config
# https://github.com/dojoengine/dojo/blob/main/examples/simple/dojo_dev.toml
#

[world]
name = "Aster (Starktember 2025)"
description = "Generative Art made with Dojo."
# icon_uri = "https://collect-code.com/assets/cc_logo/cc_logo1.png"
icon_uri = "https://collect-code.com/assets/aster/icon.jpg"
cover_uri = "https://collect-code.com/assets/aster/banner.jpg"
website = "https://collect-code.com"
seed = "aster"

[world.socials]
x = "https://x.com/matalecode"
github = "https://github.com/rsodre"
# discord = "https://discord.gg/FB2wR6uF"
# telegram = "https://t.me/dojoengine"

[env]
chain_id = "KATANA_LOCAL"
rpc_url = "http://localhost:5050"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x6c7784c9326bbec89aed58b6421d3d54ff46f7e458e080956dcdb71c5ca9867"
world_block = 1

#--------------------------
# namespaces
#
[namespace]
default = "aster"

#--------------------------
# permissions
#
[owners]
"aster" = [
  "aster-minter",
]

[writers]
"aster" = [
  "aster-minter",
  "aster-token",
]

#--------------------------
# init_calldata
#
[init_call_args]
"aster-minter" = [
  "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec", # treasury_address
  "0x0", # strk_address
]
"aster-token" = [
  "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec", # treasury_address
]
