#--------------------------
# dojo profile config
# https://book.dojoengine.org/framework/config
# https://github.com/dojoengine/dojo/blob/main/examples/simple/dojo_dev.toml
#

[world]
name = "Astraea (Starktember 2025)"
description = "Generative Art made with Dojo."
# icon_uri = "https://collect-code.com/assets/cc_logo/cc_logo1.png"
icon_uri = "https://collect-code.com/assets/aster/icon.jpg"
cover_uri = "https://collect-code.com/assets/aster/banner.jpg"
website = "https://collect-code.com"
seed = "aster"

[world.socials]
x = "https://x.com/matalecode"
github = "https://github.com/rsodre"
# discord = "https://discord.gg/FB2wR6uF"
# telegram = "https://t.me/dojoengine"

[env]
chain_id = "SN_SEPOLIA"
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia" # or env: STARKNET_RPC_URL
# account_address = ""  # env: DOJO_ACCOUNT_ADDRESS
# private_key = ""      # env: DOJO_PRIVATE_KEY
world_address = "0x7774946aab21c0b2b2484aa9a6f03bb64fd33550bb2cc8b22d46922b49af17c"
# world_block = 799759    # Karat deployment block
world_block = 2148277    # Astraea sepolia deployment block

#--------------------------
# namespaces
#
[namespace]
default = "aster"

#--------------------------
# permissions
#
[owners]
"aster" = [
  "aster-minter",
]

[writers]
"aster" = [
  "aster-minter",
  "aster-token",
]

#--------------------------
# init_calldata
#
[init_call_args]
"aster-minter" = [
  "0x020dD2C29473df564F9735B7c16063Eb3B7A4A3bd70a7986526636Fe33E8227d", # treasury_address
  "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", # strk_address
]
"aster-token" = [
  "0x020dD2C29473df564F9735B7c16063Eb3B7A4A3bd70a7986526636Fe33E8227d", # treasury_address
]
